name: Build Custom GH Pages

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
      - uses: actions/checkout@v4

      - name: Install dart sass
        uses: dw-labs-org/dart-sass-gha@v1

      - name: Build site
        run: ./build.sh

      - name: Upload GH Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/
